//
//  main.cpp
//  M6HW_1
//
//  Created by Angelina Kapiniaris on 10/11/20.
//
/*
 This program takes in three inputs from the user, and uses those values to display random number integers. The user is prompted for the minimum and maximum value, and the amount of desired values to display. Between the range, a number is randomly generated by one function, and another function is used to check if the value has a zero in it. If so, it is ommited from the output. The last function is used to count the amount of digits in each number, and adds extra spacing needed to make the columns aligned with one another.  The values are arranged in rows of ten, until they reach the desired size.
 
 Pseudocode:
 1. Declare function prototypes
 2. Declare variables in main function
 3. Prompt user for low and high values in range
 4. Prompt user for amount of values
 5. Call function that randomly generates a number in the range
 6. Implement the random number generator
 7. Check if value has a zero digit in it, omit if so.
 8. Display the value and include extra spacing based on number of digits in the value
 9. After 10 values, start a new line
 10. Display output values one-by-one until amount is reached
 11. Create repeat loop in main function
 */

#include <iostream>
#include <cstdlib>
#include <cmath>
using namespace std;

// function prototypes
int numberGenerator(int low, int high);
int digitCounter(int randomNum);
bool checkZeros(int randomNum);

int main()
{
    srand((unsigned) time(0)); //generator seed
    // declare variables
    int low = 0;
    int high = 0;
    int amount = 0;
    int randomNum = 0;
    char repeat = 'y';
    
    while (repeat == 'y') //repeat loop
    {
        cout << "Enter two positive integers for the range: ";
        cin >> low >> high; // prompt user for min and max
        
        cout << "How many random numbers would you like to generate? ";
        cin >> amount; // prompt user for size
        cout << endl;
        
        cout << "100 randomly generated numbers in the range " << low << " to " << high << " are as follows. \n";
        
        for (int i = 1; i <= amount; i++) // loop for displayed values
        {
            randomNum = numberGenerator(low, high); // call function that picks number
            
            cout << randomNum << " ";
            
            int padding = 6; //desired spacing
            
            for (int i = 0; i < padding - digitCounter(randomNum); i++)
            {
                cout << " "; // produce extra spacing needed
            }
            
            if (i % 10 == 0) // start a new line after ten values
                cout << endl;
            
        }
        
        cout << endl;
        cout << endl;
        cout << "Would you like to generate different numbers (y/n)? ";
        cin >> repeat;
        cout << endl;
    }
    cout << "Thank you for using this program. Goodbye! \n";
    
    return 0;
}

int numberGenerator(int low, int high)
{
    // random number generator
    int randomNum = (rand()%(high - low + 1))+ low;
    
    while (checkZeros(randomNum)) // call zeros function
    {
        randomNum = (rand()%(high - low + 1))+ low;
        if (true)
            continue; //try generator again
        else
            break;
    }
    
    
    return randomNum;
}

int digitCounter(int randomNum)
{
    // check how many digits in the value
    int digit = 0;
    while (randomNum > 0)
    {
        digit++;
        randomNum /= 10;
    }
    
    return digit;
}


bool checkZeros(int randomNum)
{
    // check if value has a zero digit
    while (randomNum > 0)
    {
        if (randomNum % 10 == 0)
        {
            //if zero, return true
            return true;
        }
        randomNum /= 10;
    }
    // if no zero, return false
    return false;
}

